apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${{ values.repoName }}-app
  namespace: openshift-gitops
spec:
  generators:      
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: ${{ values.environment }}-placement
      requeueAfterSeconds: 180
  
  template:
    metadata:
      name: 
    spec:
      source:
        repoURL: https://${{ values.sourceControl }}/${{ values.orgName }}/${{ values.repoName }}
        path: deploy/k8s/overlays/${{ values.environment }}
        targetRevision: main

      destination:
        namespace: ${{ values.namespace }}
        server: {{ server }}
    
    project: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false