{%- if values.ingressClassName and values.host %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.repoName }}-ingress
  labels:
    app: ${{ values.repoName }}
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: ${{ values.repoName }}
spec:
  ingressClassName: ${{ values.ingressClassName }}
  - host: ${{ values.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ${{ values.repoName }}
              port:
                number: ${{ values.port }}
{%- endif %}