name: ci

on:
  push:
    branches:
      - main
    paths:
      - "source"
  workflow_dispatch:
    
env:
  IMAGE_TAGS: ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: get repo name
      run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
    - name: build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.REPO_NAME }} 
        tags: ${{ env.IMAGE_TAGS }}
        context: source
        containerfiles: |
          source/cmd/server/Dockerfile
    - name: push image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
    
