apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
    name: apispec-catalog
    title: Template to catalog API specifications
    description: This template can be used for cataloging all API specifications. Specs are stored in a Git repository 
spec:
    owner: janus-authors
    system: janus-idp
    type: service

    parameters:
    - title: Provide information about API spec
      required:
      - org
      - repoName
      - reviewers
      - pr_branch  
      properties:
        org:
          title: Org
          type: string
          description: GitHub Org
        repoName:
          title: Repository Name
          type: string
          description: Repository where the api specifications are stored
        reviewers:
          title: Reviewers
          type: array
          items:
            type: string
            ui:field: EntityPicker
            ui:options:
              catalogFilter:
                kind: [User, Group]
          uniqueItems: true
          description: Select list of users that need to review this API specification 
        spec:
          title: Api specification
          type: string
          format: data-url
          ui:options:
            accept:
            - .yaml
            - .yml
            - .json
        pr_branch:
          title: PR branch
          type: string
          description: Pull Request Branch
    steps:
    - id: log-parameters
      name: log parameter values
      action: debug:log
      input:
        message: |
          'Repository URL: ${{ parameters.repoUrl }}'
          'Reviewers: ${{ parameters.reviewers }}'
          'Spec: ${{ parameters.spec }}'  
    - id: fetch-repo
      name: fetch repo
      action: fetch:plain
      input:
        url: https://github.com/${{ parameters.org }}/${{ parameters.repoName }}
    #- id: open-pr
    #  name: Open pull request
    #  action: publish:github:pull-request
    #  input:
    #    branchName: ${{ parameters.pr_branch }}
    #    title: 'PR'
    #    description: 'Pull request created by Backstage scaffolder'
    #output:
    #  links:
    #  - title: PR Url
    #    url: ${{ steps["open-pr"].output.remoteUrl }}